name: msds2025-ml3-review
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - matplotlib=3.9.4
  - pandas=2.2.3
  - ipykernel=6.29.5
  - python=3.9
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - pip=25.1.1
  - scipy=1.13.1
  - openpyxl=3.1.5
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - cuda-nvcc=12.4.131
  - keras=2.13.1
  - tensorflow-gpu=2.13.1
  - numpy=1.26.4
  - pip:
    - ipywidgets==8.1.7
    - pydot==1.4.2
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/lib/'"
